include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  plugins:
    - custom_lint
    
linter:
  rules:
    # カスタムルール
    prefer_single_quotes: true
    avoid_print: true
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    
    # Riverpod関連
    riverpod_final_provider: true