include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
  plugins:
    - custom_lint
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
    
linter:
  rules:
    # Dart 3.9の新機能を活用
    prefer_single_quotes: true
    avoid_print: true
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    
    # Records & Patterns（Dart 3.0+）
    prefer_expression_function_bodies: true
    prefer_final_locals: true
    prefer_final_fields: true
    
    # 最新のベストプラクティス
    use_super_parameters: true
    unnecessary_parenthesis: true
    avoid_redundant_argument_values: true
    prefer_relative_imports: true
    
    # Riverpod関連（カスタムlintが有効な場合）
    # riverpod_final_provider: true