name: task_aiagent
description: "TimeFlow - AIタスク管理アプリ"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.3.0  # 現在のDart SDKに合わせて修正
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # 状態管理
  flutter_riverpod: ^2.4.0  # 3.0.0は Dart SDK 3.4.0以上が必要
  riverpod_annotation: ^2.3.0
  
  # Firebase（バージョンダウン）
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0
  firebase_analytics: ^10.7.0
  cloud_functions: ^4.6.0
  
  # UI/UX
  material_color_utilities: ^0.11.1  # バージョン指定追加
  go_router: ^12.1.0  # 16.2.1は新しすぎる
  
  # ローカルストレージ
  shared_preferences: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # HTTP通信
  dio: ^5.3.0
  
  # 日時処理
  intl: ^0.18.1  # 0.20.2は新しすぎる
  timezone: ^0.9.2
  
  # カレンダー連携
  google_sign_in: ^6.1.0  # 7.1.1は新しすぎる
  googleapis: ^11.4.0  # 14.0.0は新しすぎる
  device_calendar: ^4.3.1
  
  # 通知
  flutter_local_notifications: ^15.1.0  # 18.0.1は新しすぎる
  
  # AI/ML
  tflite_flutter: ^0.10.0  # 0.11.0は新しすぎる
  
  # その他ユーティリティ
  uuid: ^3.0.7  # 4.5.1は新しすぎる
  path_provider: ^2.1.0
  permission_handler: ^10.4.0  # 12.0.1は新しすぎる
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # コード生成
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.0  # 3.0.0-dev.11は開発版で不安定
  hive_generator: ^2.0.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  
  # テスト
  mockito: ^5.4.2
  integration_test:
    sdk: flutter
  
  # コード品質
  flutter_lints: ^3.0.0  # 6.0.0は新しすぎる
  very_good_analysis: ^5.1.0  # 9.0.0は新しすぎる

flutter:
  uses-material-design: true
  
  # アセット設定（必要に応じて後で追加）
  # assets:
  #   - assets/images/
  #   - assets/icons/
  
  # フォント設定（必要に応じて後で追加）
  # fonts:
  #   - family: NotoSansJP
  #     fonts:
  #       - asset: assets/fonts/NotoSansJP-Regular.ttf