name: task_aiagent
description: "TimeFlow - AIタスク管理アプリ"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # 状態管理
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  
  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  firebase_analytics: ^12.0.1
  cloud_functions: ^6.0.1
  
  # UI/UX
  material_color_utilities: 
  go_router: ^16.2.1
  
  # ローカルストレージ
  shared_preferences: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # HTTP通信
  dio: ^5.3.0
  
  # 日時処理
  intl: ^0.20.2
  timezone: ^0.9.2
  
  # カレンダー連携
  google_sign_in: ^7.1.1
  googleapis: ^14.0.0
  device_calendar: ^4.3.1
  
  # 通知
  flutter_local_notifications: ^18.0.1
  
  # AI/ML
  tflite_flutter: ^0.11.0
  
  # その他ユーティリティ
  uuid: ^4.5.1
  path_provider: ^2.1.0
  permission_handler: ^12.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # コード生成
  build_runner: ^2.4.7
  riverpod_generator: ^3.0.0-dev.11
  hive_generator: ^2.0.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  
  # テスト
  mockito: ^5.4.2
  integration_test:
    sdk: flutter
  
  # コード品質
  flutter_lints: ^6.0.0
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true