name: task_aiagent
description: "TimeFlow - AIタスク管理アプリ"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.2.6  # 最新のDart SDK要件
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # 状態管理
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Firebase（段階的に追加）
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  
  # UI/UX
  
  go_router: ^13.2.1
  
  # 日時処理
  intl: ^0.19.0
  
  # ユーティリティ
  uuid: ^4.3.3
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # コード生成
  build_runner: ^2.4.8
  riverpod_generator: ^2.4.0
  
  # コード品質
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true